Repository Diegogagan2587/Book-a-concert-front-end, pull requests merged in 2023-11, with the labels that each got.

#17 Feat/buttons
  index.html
  src/components/buttons/LeftButton.jsx
  src/components/buttons/RightButton.jsx
  src/components/buttons/RoundedButton.jsx
Labels: enhancement

#19 Feat/reserve concert page [ Layout Only ]
  src/components/buttons/DropDownSelect.jsx
  src/pages/ReserveConcertPage.jsx
Labels: enhancement

#21 Feat/item page or concert details [ Logic ]
  src/components/ItemDataPanel.jsx
  src/pages/ConcertDetailsPage.jsx
  src/redux/concertDetails/concertDetailsSlice.js
  src/redux/requests/getConcert.js
  src/redux/store.js
Labels: enhancement

#23 Log in - FrontEnd
  src/App.jsx
  src/components/Login.jsx
  src/redux/slices/userSlice.js
  src/redux/store.js
Labels: enhancement

#22 Reserve form - FrontEnd [ Logic Only ] - [ 1px ]
  src/components/buttons/DropDownSelect.jsx
  src/components/buttons/RoundedButton.jsx
  src/pages/ReserveConcertPage.jsx
  src/redux/requests/getConcerts.js
  src/redux/requests/postReservation.js
  src/redux/reservationForm/reservationFormSlice.js
  src/redux/store.js
Labels: enhancement

#25 Main Page / All items / Concerts - FronEnd
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/Authentication.jsx
  src/pages/ConcertDetailsPage.jsx
  src/pages/MainPage.jsx
Labels: enhancement

#27 Navigation Pannel/Functionality Only - FronEnd
  src/App.jsx
  src/components/NavigationPanel.jsx
  src/redux/slices/userSlice.js
Labels: enhancement

#30 Add and Delent Concert Sections - FrontEnd
  src/App.jsx
  src/pages/AddConcertPage.jsx
  src/pages/DeleteConcertPage.jsx
  src/pages/ReserveConcertPage.jsx
  src/redux/slices/concertSlice.js
  src/redux/store.js
Labels: enhancement

#32 My reservations: Add basic style
  src/App.jsx
  src/pages/MyReservationsPage.jsx
  src/stylesheets/MyReservationsPage.css
Labels: enhancement

#31 feat/navigation-style
  src/App.jsx
  src/components/NavigationPanel.jsx
Labels: enhancement

#36 Fix Organizer_name within ConcertDataPanel
  src/components/ItemDataPanel.jsx
Labels: bug

#37 Fix: Transform the image of Main page to fill the parent container
  src/pages/MainPage.jsx
Labels: bug, enhancement

#38 Fix/height-concert-detals
  src/pages/ConcertDetailsPage.jsx
Labels: bug

#40 Fix Reserve form: Will reserve for /current_user
  src/pages/ReserveConcertPage.jsx
Labels: bug

#41 Feat/readme
  LICENSE
  README.md
Labels: documentation

#39 Style - Add - Delete Concert Pages
  src/assets/img/festival.jpg
  src/assets/img/red-festival.jpg
  src/pages/AddConcertPage.jsx
  src/pages/DeleteConcertPage.jsx
  src/stylesheets/AddConcertPage.css
  src/stylesheets/DeleteConcertPage.css
Labels: enhancement

#44 Improve user feedback on sign up page
  src/components/Login.jsx
  src/components/Signup.jsx
  src/redux/slices/userSlice.js
Labels: bug, enhancement

#43 Book a Concert V1.0
  .babelrc
  .eslintrc.cjs
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  LICENSE
  README.md
  index.html
  kanban.png
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/img/festival.jpg
  src/assets/img/pexels-photo-1387174.jpeg
  src/assets/img/red-festival.jpg
  src/assets/react.svg
  src/components/Authentication.jsx
  src/components/ItemDataPanel.jsx
  src/components/Login.jsx
  src/components/NavigationPanel.jsx
  src/components/Signup.jsx
  src/components/buttons/DropDownSelect.jsx
  src/components/buttons/LeftButton.jsx
  src/components/buttons/RightButton.jsx
  src/components/buttons/RoundedButton.jsx
  src/index.css
  src/main.jsx
  src/pages/AddConcertPage.jsx
  src/pages/ConcertDetailsPage.jsx
  src/pages/DeleteConcertPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyReservationsPage.jsx
  src/pages/ReserveConcertPage.jsx
  src/redux/concertDetails/concertDetailsSlice.js
  src/redux/requests/getConcert.js
  src/redux/requests/getConcerts.js
  src/redux/requests/getOrganizers.js
  src/redux/requests/postReservation.js
  src/redux/reservationForm/reservationFormSlice.js
  src/redux/slices/concertSlice.js
  src/redux/slices/userSlice.js
  src/redux/store.js
  src/stylesheets/AddConcertPage.css
  src/stylesheets/DeleteConcertPage.css
  src/stylesheets/Login.css
  src/stylesheets/MyReservationsPage.css
  tailwind.config.js
  vite.config.js
Labels: enhancement

#46 Fix/refactor global state
  src/App.jsx
  src/components/buttons/DropDownSelect.jsx
  src/pages/AddConcertPage.jsx
  src/pages/ConcertDetailsPage.jsx
  src/pages/DeleteConcertPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyReservationsPage.jsx
  src/pages/ReserveConcertPage.jsx
  src/redux/concertDetails/concertDetailsSlice.js
  src/redux/requests/getOrganizers.js
  src/redux/requests/getReservations.js
  src/redux/slices/concertSlice.js
  src/redux/slices/reservationSlice.js
  src/redux/slices/userSlice.js
  src/redux/store.js
Labels: bug
